services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=${LOCAL_DB_PASSWORD}
      - POSTGRES_USER=${LOCAL_DB_USER}
      - POSTGRES_DB=${LOCAL_DB_NAME}
    ports:
      - ${LOCAL_DB_PORT}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data